[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

solc_version = "0.8.27"
optimizer = true
optimizer_runs = 200

fs_permissions = [
    { access = "read", path = "./out/"},
    { access = "read", path = "./script/input/"},
    { access = "read-write", path = "./script/output/"},
    { access = "write", path = "./reports" }
]

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-v5.1.0/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable-v5.1.0/contracts/",
    "operator-filter-registry/=lib/operator-filter-registry/",
    "openzeppelin-foundry-upgrades/=lib/openzeppelin-foundry-upgrades/src/"
]

[rpc_endpoints]
localhost = "http://127.0.0.1:9545"
